insert into gender values(1,'Female');
insert into gender values(2,'Male');
insert into gender values(3,'Others');
insert into user_type values(1,'Student');
insert into user_type values(2,'Profestional');
insert into address_type values(1,'Home');
insert into address_type values(2,'office');
insert into address_type values(3,'Other');
insert into course_domain values (1,'Cloud');
insert into course_domain values(2,'Data Engineering');
insert into course_domain values(3,'Machine Learning');
insert into course_domain values(4,'DevOps');
insert into course_domain values(5,'Frontend');
insert into course_domain values(6,'Backend');
insert into author values(1,'Max scheduler');
insert into author values(2,'‎Kirill Eremenko');
insert into author values(3,'Ashraf Said');
insert into author values(4,'Deborah Grayson');
commit;